import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* ========== ORIGINAL CODE (BEFORE FIX) ==========
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
          Problem: Browser extensions (like Grammarly) add attributes to <body> after hydration,
          causing a React SSR mismatch error. suppressHydrationWarning tells React to ignore this.
      ========== END ORIGINAL CODE ========== */}

      {/* ========== NEW CODE (FIXED FIX) ==========
          Added suppressHydrationWarning to allow browser extensions to modify body attributes
          without breaking React hydration. This is safe because body attributes don't affect app logic.
      ========== */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        {children}
      </body>
      {/* ========== END NEW CODE ========== */}
    </html>
  );
}
